import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/navbars/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-[#030303] text-zinc-100">
        <div className="flex min-h-screen min-w-screen">
          <div className="flex min-h-screen flex-1 flex-col">
            <TopNav />
            <main className="mx-auto flex w-full max-w-7xl flex-1 px-4 py-4">
              {/* This is where your “Reddit-like” content / feeds go */}
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
